# Generated by Django 4.2.2 on 2023-07-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_propietario_alter_departamento_edificio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edificio',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('negocio', 'Negocio'), ('público', 'Público')], max_length=30),
        ),
    ]
