# Generated by Django 4.2.2 on 2023-07-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_edificio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='costo',
            field=models.IntegerField(),
        ),
    ]
